FROM node:21.7.1-alpine

WORKDIR /RMPweb
COPY package.json .
RUN npm ci --force
COPY . .
RUN npm run build
# maybe command to delete not needed files after build
# Using default root user
CMD ["node", "build/index.js"]
