services:
  sveltekit:
    build:
      context: RMPweb/
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    networks:
      - fullstack

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name : kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - fullstack

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      #for testing
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - fullstack
volumes:
  data:
networks:
  fullstack:
    driver: bridge

